devtools: download scripts from linux if not found
Both checkpatches.sh and get-maintainer.sh require scripts that come
from the linux sources. And they require DPDK_*_PATH variables to be set
to point at these scripts locally. For new contributors this can be
tedious since they will have to clone the whole linux sources just to
have simple perl scripts.

Update checkpatches.sh and get-maintainer.sh to have them download the
upstream scripts if they are not found locally. Store the downloaded
scripts in the .git/ folder so that they are found for future runs.

If either DPDK_CHECKPATCH_PATH or DPDK_GETMAINTAINER_PATH are set, they
will be used in priority.

Signed-off-by: Robin Jarry <rjarry@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>

diff --git a/devtools/load-devel-config b/devtools/load-devel-config
--- a/devtools/load-devel-config
+++ b/devtools/load-devel-config
@@ -1,4 +1,5 @@
 # SPDX-License-Identifier: BSD-3-Clause
+# vim: ft=sh
 
 # This file is intended to be sourced into shell
 
@@ -14,3 +15,47 @@ test ! -r $(dirname $(readlink -f $0))/../.develconfig ||
         . $(dirname $(readlink -f $0))/../.develconfig
 
 # The config files must export variables in the shell style
+
+# This function is called to download missing scripts by subcommands
+#
+# Example:
+#   download_script DPDK_CHECKPATCH_PATH \
+#       https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl
+download_script() { # <var_name> <url>
+	var_name=$1
+	url=$2
+
+	script_name=$(basename "$url")
+	git_dir=$(git rev-parse --git-dir) || return 1
+	dl_path="$git_dir/$script_name"
+
+	if [ -f "$dl_path" ] && [ -x "$dl_path" ]; then
+		eval "$var_name='$dl_path'"
+		return 0
+	fi
+
+	if ! [ -t 0 ]; then
+		# not in an interactive terminal, abort
+		return 1
+	fi
+	prompt="Download $url and set $var_name=$dl_path? [y/n] "
+
+	while printf '%s' "$prompt" && read y && ! [ "$y" = y ]; do
+		if [ "$y" = n ]; then
+			return 1
+		fi
+	done
+
+	if which curl >/dev/null 2>&1; then
+		curl -Lo "$dl_path" "$url" || return 1
+	elif which wget >/dev/null 2>&1; then
+		wget -O "$dl_path" "$url" || return 1
+	else
+		echo "error: neither curl nor wget are available." >&2
+		return 1
+	fi
+	chmod 755 "$dl_path" || return 1
+
+	eval "$var_name='$dl_path'"
+	return 0
+}
